service: api-stmj

frameworkVersion: "2"

provider:
  name: aws
  runtime: nodejs10.x
  profile: serverless-admin-paroquia
  memorySize: 256
  timeout: 30
  environment:
    MASS_TABLE_NAME: stmj_mass_${opt:stage, self:provider.stage}
    PERSON_TABLE_NAME: stmj_person_${opt:stage, self:provider.stage}
    LOCK_TABLE_NAME: distributed_locks_store_${opt:stage, self:provider.stage}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.MASS_TABLE_NAME}"
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.PERSON_TABLE_NAME}"
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.LOCK_TABLE_NAME}"

functions:
  create-mass:
    handler: src/endpoints/stmj-create-mass/index.handler
    events:
      - http:
          path: "mass"
          method: post
          cors: true
          authorizer: aws_iam

  create-masses-at-date:
    handler: src/endpoints/stmj-create-masses-at-date/index.handler
    events:
      - http:
          path: "mass/createatdate"
          method: post
          cors: true
          authorizer: aws_iam
    environment:
      TOTAL_VACANCIES: "69"

  create-person:
    handler: src/endpoints/stmj-create-person/index.handler
    events:
      - http:
          path: "person"
          method: post
          cors: true
          authorizer: aws_iam

  create-scheduling:
    handler: src/endpoints/stmj-create-scheduling/index.handler
    events:
      - http:
          path: "scheduling"
          method: post
          cors: true
          authorizer: aws_iam

  create-scheduling-batch:
    handler: src/endpoints/stmj-create-scheduling-batch/index.handler
    events:
      - http:
          path: "scheduling_batch"
          method: post
          cors: true
          authorizer: aws_iam

  delete-scheduling:
    handler: src/endpoints/stmj-delete-scheduling/index.handler
    events:
      - http:
          path: "scheduling/delete"
          method: post
          cors: true
          authorizer: aws_iam

  get-mass:
    handler: src/endpoints/stmj-get-mass/index.handler
    events:
      - http:
          path: "mass/{massId}"
          method: get
          cors: true
          authorizer: aws_iam

  get-masses-by-date-range:
    handler: src/endpoints/stmj-get-masses-by-date-range/index.handler
    events:
      - http:
          path: "mass"
          method: get
          cors: true
          authorizer: aws_iam

  get-mass-people:
    handler: src/endpoints/stmj-get-mass-people/index.handler
    events:
      - http:
          path: "mass/{massId}/people"
          method: get
          cors: true
          authorizer: aws_iam

  get-mass-people-xlsx:
    handler: src/endpoints/stmj-get-mass-people-xlsx/index.handler
    events:
      - http:
          path: "mass/{massId}/people/xlsx"
          method: get
          cors: true
          authorizer: aws_iam

  get-permissions:
    handler: src/endpoints/stmj-get-permissions/index.handler
    events:
      - http:
          path: "permissions"
          method: get
          cors: true
          authorizer: aws_iam
    environment:
      ADMINS: '["guiavenas@gmail.com"]'

  get-person-by-email:
    handler: src/endpoints/stmj-get-person-by-email/index.handler
    events:
      - http:
          path: "person/email/{email}"
          method: get
          cors: true
          authorizer: aws_iam

  get-person-masses:
    handler: src/endpoints/stmj-get-person-masses/index.handler
    events:
      - http:
          path: "person/masses"
          method: get
          cors: true
          authorizer: aws_iam

resources:
  Resources:
    MassTable:
      Type: "AWS::DynamoDB::Table"
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: uuid
            AttributeType: S
        KeySchema:
          - AttributeName: uuid
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
        TableName: ${self:provider.environment.MASS_TABLE_NAME}

    PersonTable:
      Type: "AWS::DynamoDB::Table"
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: uuid
            AttributeType: S
        KeySchema:
          - AttributeName: uuid
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
        TableName: ${self:provider.environment.PERSON_TABLE_NAME}

    DistributedLocksStore:
      Type: "AWS::DynamoDB::Table"
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
        TableName: ${self:provider.environment.LOCK_TABLE_NAME}
